apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-apps
  labels:
    app: app1
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 20%
    type: RollingUpdate
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      name: todo-app
      labels:
        app: app1
    spec:
      containers:
        - name: nodesample
          image: nikdoocker2293/demo:v1
          ports:
            - containerPort: 3000
      resources:
        limits:
          memory: "500Mi"
          cpu: "300m"
        requests:
          memory: "200Mi"
          cpu: "200m"
